# Generated by Django 4.1.4 on 2022-12-18 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zipcodeapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zipcode',
            name='state',
            field=models.CharField(max_length=100),
        ),
    ]
