# Generated by Django 4.1.4 on 2022-12-18 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zipcodeapi', '0002_alter_zipcode_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zipcode',
            name='id',
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='zipcode',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
